# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function() {
    invisible(.Call(`_cgalPolynomials_test`))
}

test2 <- function(Powers, Coeffs) {
    invisible(.Call(`_cgalPolynomials_test2`, Powers, Coeffs))
}

test3 <- function(Powers, Coeffs) {
    .Call(`_cgalPolynomials_test3`, Powers, Coeffs)
}

